"""add timeout alerts to webhook config

Revision ID: 28b844700e7a
Revises: 7d1b333a4362
Create Date: 2026-04-08 16:12:57.026074

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "28b844700e7a"
down_revision = "7d1b333a4362"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_created_at"), ["created_at"], unique=False)

    with op.batch_alter_table("webhook_config", schema=None) as batch_op:
        batch_op.add_column(sa.Column("timeout_alerts_enabled", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("timeout_hours", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("timeout_ticket_id", sa.Integer(), nullable=True))

    with op.batch_alter_table("webhook_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_webhook_log_config_id"), ["config_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_webhook_log_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_webhook_log_request_id"), ["request_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_webhook_log_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webhook_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webhook_log_status"))
        batch_op.drop_index(batch_op.f("ix_webhook_log_request_id"))
        batch_op.drop_index(batch_op.f("ix_webhook_log_created_at"))
        batch_op.drop_index(batch_op.f("ix_webhook_log_config_id"))

    with op.batch_alter_table("webhook_config", schema=None) as batch_op:
        batch_op.drop_column("timeout_ticket_id")
        batch_op.drop_column("timeout_hours")
        batch_op.drop_column("timeout_alerts_enabled")

    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_created_at"))

    # ### end Alembic commands ###
