"""Add last_stale_alert_at to WebhookConfig

Revision ID: 3f8d9c123abc
Revises: 28b844700e7a
Create Date: 2026-04-09 13:16:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3f8d9c123abc"
down_revision = "28b844700e7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c["name"] for c in inspector.get_columns("webhook_config")]
    
    if "last_stale_alert_at" not in columns:
        with op.batch_alter_table("webhook_config", schema=None) as batch_op:
            batch_op.add_column(sa.Column("last_stale_alert_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webhook_config", schema=None) as batch_op:
        batch_op.drop_column("last_stale_alert_at")
    # ### end Alembic commands ###
