"""add summary_remove_strings

Revision ID: 7d1b333a4362
Revises: 49f76b520c64
Create Date: 2026-02-24 15:58:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7d1b333a4362'
down_revision = '49f76b520c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_remove_strings', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_config', schema=None) as batch_op:
        batch_op.drop_column('summary_remove_strings')

    # ### end Alembic commands ###
