"""Initial migration

Revision ID: 8ed2564b4bb6
Revises: 
Create Date: 2026-02-11 00:47:56.932809

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8ed2564b4bb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('config_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bearer_token', sa.String(length=512), nullable=False),
    sa.Column('customer_id_default', sa.String(length=50), nullable=True),
    sa.Column('board', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('ticket_type', sa.String(length=100), nullable=True),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('item', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=100), nullable=True),
    sa.Column('trigger_field', sa.String(length=100), nullable=True),
    sa.Column('open_value', sa.String(length=50), nullable=True),
    sa.Column('close_value', sa.String(length=50), nullable=True),
    sa.Column('ticket_prefix', sa.String(length=100), nullable=True),
    sa.Column('json_mapping', sa.Text(), nullable=True),
    sa.Column('routing_rules', sa.Text(), nullable=True),
    sa.Column('maintenance_windows', sa.Text(), nullable=True),
    sa.Column('trusted_ips', sa.Text(), nullable=True),
    sa.Column('last_rotated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('config_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['webhook_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_log')
    op.drop_table('webhook_config')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
