"""Add GlobalMapping model

Revision ID: b7c8d9e0f1a2
Revises: f3a1d2c6e5b4
Create Date: 2026-02-19 16:35:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7c8d9e0f1a2"
down_revision = "f3a1d2c6e5b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_mapping",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_value", sa.String(length=255), nullable=False),
        sa.Column("company_id", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_global_mapping_tenant_value"), "global_mapping", ["tenant_value"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_global_mapping_tenant_value"), table_name="global_mapping")
    op.drop_table("global_mapping")
    # ### end Alembic commands ###
